### ISSUE TITLE
"Invalid URL" on a valid URL

### ISSUE THREAD

**Issue by ReneR97** [phamleduy04/follow-redirects-fast#16]
hey, love your package, but i found a really odd bug, or atleast i think its one. 
When i use the following URL "http://www.sunela.com" i get a "Invalid URL" error, even though the URL is valid. 
if i remove the "a" from it so its "http://www.sunel.com" it works just fine. 
And if a add a character at the end, for example a "x" so its http://www.sunelax.com, it tells me the URL doesnt exist. 

so it works as intendet every other time, but not with the original URL "http://www.sunela.com".

I just use the sample code as follows to test it: 
await followRedirects({ url: 'http://www.sunela.com', maxRedirects: 10, timeout: 5000 });

**Comment by ReneR97** [comment]
found the issue, made a pull request that would fix it

**Comment by phamleduy04** [comment]
ty for the issue, after work I will review and merge #17 🎉
